app = 'rl-enzyme'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile.cuda"

[[vm]]
  size = 'a100-40gb'
  memory = '64gb'
  
[[mounts]]
source = "projects"
destination = "/root/projects"
initial_size = "40GB"
auto_extend_size_threshold = 80
auto_extend_size_increment = "5GB"

[[services]]
  internal_port = 2222
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  [[services.ports]]
    port = 22
