app = 'rl-enzyme'
primary_region = 'ord'

[build]
  dockerfile = "Dockerfile.cuda"

[[vm]]
  size = 'a100-40gb'
  
[[mounts]]
source = "data"
destination = "/data"

[[services]]
  internal_port = 2222
  protocol = "tcp"
  auto_stop_machines = true
  auto_start_machines = true
  [[services.ports]]
    port = 22