experiment:
  wildtype_AA_seq: "MSTETLRLQKARATEEGLAFETPGGLTRALRDGCFLLAVPPGFDTTPGVTLCREFFRPVEQGGESTRAYRGFRDLDGVYFDREHFQTEHVLIDGPGRERHFPPELRRMAEHMHELARHVLRTVLTELGVARELWSEVTGGAVDGRGTEWFAANHYRSERDRLGCAPHKDTGFVTVLYIEEGGLEAATGGSWTPVDPVPGCFVVNFGGAFELLTSGLDRPVRALLHRVRQCAPRPESADRFSFAAFVNPPPTGDLYRVGADGTATVARSTEDFLRDFNERTWGDGYADFGIAPPEPAGVAEDGVRA"
  ligand_smile: "OC(=O)CCc1ccccc1"
  # subSmiles = ['CC(=O)CCc1ccccc1', 'OC(=O)CCc1ccccc1', 'COc1cccc(CCC(O)=O)c1', 'COc1cc(CCCO)ccc1O', 'COc1cc(CCC(O)=O)ccc1O', 'OC(=O)CCc1ccc2OCOc2c1', 'COc1cc(CCCO)cc(OC)c1O', 'OC(=O)Cc1ccccc1', 'CC(=O)CCc1ccc2OCOc2c1']
  device: "cuda"
agents:
  sequence_edit_target_ratio: 0.05
  epochs: 10
  steps_per_epoch: 100
  episode_per_collect: 3
  batch_size: 100 
  repeat_per_collect: 1
  ppo:
    eps: 0.1 # 0.2
    value_clip: True
    advantage_normalization: True
    recompute_advantage: False
    reward_normalization: True
    vf_coef: 0.5
    ent_coef: 0.01
    max_grad_norm: 0.5
    gae_lambda: 0.95
    discount_factor: 0.99
  replayBuffer:
    total_size: 10000
  adam:
    learning_rate: 2.5e-4
    epsilon: 1e-5
evodiff:
  model_size_parameters: 640
  mutations: 5
alphaflow:
  ckpt: "/root/projects/rl-enzyme-engineering/ckpts/AlphaFlow/esmflow_md_distilled_202402.pt"
  samples: 1
  noisy_first: True
  no_diffusion: True
  self_cond: False
  tmax: 0.1
  steps: 10
fabind:
  ckpt: "/root/projects/rl-enzyme-engineering/ckpts/FABind/FABind_plus/fabind_plus_best_ckpt.bin"
  seed: 244
  batch_size: 8
  sample_size: 10
  post_optim: True
dsmbind:
  ckpt: "fasdf"
hydra:
  run:
    dir: ../experiments/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    chdir: True
  verbose: False